HTTP/1.0 429 Too Many Requests
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
  <body>
    <h1>429 Too Many Requests</h1>
    <p>You have exceeded the request rate limit. Please try again later.</p>
  </body>
</html>